name : CI

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        name: 'Build and Push'
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: generate SHA
              id: generate_sha
              run: |
                SHA=$(echo $GITHUB_SHA | head -c7)
                echo "sha=$SHA" >> $GITHUB_OUTPUT
            
            - name: Login into the container registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build docker image
              run: docker build -t ph3523/nlw.journey.api:${{ steps.generate_sha.outputs.sha }} .

            - name: Push image
              run: |
                docker push ph3523/nlw.journey.api:${{ steps.generate_sha.outputs.sha }}
                docker tag ph3523/nlw.journey.api:${{ steps.generate_sha.outputs.sha }} ph3523/nlw.journey.api:latest
                docker push ph3523/nlw.journey.api:latest